spring.application.name=identity-modulith


# =========================
# PostgreSQL DataSource
# =========================
spring.datasource.url=jdbc:postgresql://1.224.162.188:51445/nexfron
spring.datasource.username=admin
spring.datasource.password=nexfron11!
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA / Hibernate ??
# =========================
# ??? ?? ?? ??
# - ??/???: update
# - ??/?? DB: validate ?? none ??
spring.jpa.hibernate.ddl-auto=update

# PostgreSQL ??
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ??? SQL ??
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
